export const christmasLofiPlaylist = [
  { id: 'arctic-quiet-nights', title: 'Arctic Quiet Nights', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Arctic%20Quiet%20Nights.mp3' },
  { id: 'blankets-bells', title: 'Blankets & Bells', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Blankets%20&%20Bells.mp3' },
  { id: 'candlelight-drifts', title: 'Candlelight Drifts', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Candlelight%20Drifts.mp3' },
  { id: 'caramel-winter-latte', title: 'Caramel Winter Latte', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Caramel%20Winter%20Latte.mp3' },
  { id: 'chimney-smoke-dreams', title: 'Chimney Smoke Dreams', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Chimney%20Smoke%20Dreams.mp3' },
  { id: 'christmas-midnight-drive', title: 'Christmas Midnight Drive', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Christmas%20Midnight%20Drive.mp3' },
  { id: 'cold-hands-warm-loops', title: 'Cold Hands, Warm Loops', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Cold%20Hands,%20Warm%20Loops.mp3' },
  { id: 'cozy-cabin-echoes', title: 'Cozy Cabin Echoes', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Cozy%20Cabin%20Echoes.mp3' },
  { id: 'cozy-claus', title: 'Cozy Claus', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Cozy%20Claus.mp3' },
  { id: 'cozy-holiday', title: 'Cozy Holiday', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Cozy%20Holiday.mp3' },
  { id: 'december-daydreams', title: 'December Daydreams', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/December%20Daydreams.mp3' },
  { id: 'downtown-christmas-market', title: 'Downtown Christmas Market', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Downtown%20Christmas%20Market.mp3' },
  { id: 'eggnog-echoes', title: 'Eggnog & Echoes', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Eggnog%20&%20Echoes.mp3' },
  { id: 'emberlight-echoes', title: 'Emberlight Echoes', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Emberlight%20Echoes.mp3' },
  { id: 'emotional-evergreen', title: 'Emotional Evergreen', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Emotional%20Evergreen.mp3' },
  { id: 'evening-ember-beats', title: 'Evening Ember Beats', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Evening%20Ember%20Beats.mp3' },
  { id: 'fireside-comfort', title: 'Fireside Comfort', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Fireside%20Comfort.mp3' },
  { id: 'forest-cabin-latte', title: 'Forest Cabin Latte', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Forest%20Cabin%20Latte.mp3' },
  { id: 'frostbitten-letters', title: 'Frostbitten Letters', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Frostbitten%20Letters.mp3' },
  { id: 'frosted-starlight', title: 'Frosted Starlight', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Frosted%20Starlight.mp3' },
  { id: 'frosted-window', title: 'Frosted Window', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Frosted%20Window.mp3' },
  { id: 'frosty-breath', title: 'Frosty Breath', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Frosty%20Breath.mp3' },
  { id: 'frozen-footsteps', title: 'Frozen Footsteps', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Frozen%20Footsteps.mp3' },
  { id: 'gingerbread', title: 'Gingerbread', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Gingerbread.mp3' },
  { id: 'holiday-espresso', title: 'Holiday Espresso', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Holiday%20Espresso.mp3' },
  { id: 'holiday-heartbeats', title: 'Holiday Heartbeats', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Holiday%20Heartbeats.mp3' },
  { id: 'holiday-heartstrings', title: 'Holiday Heartstrings', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Holiday%20Heartstrings.mp3' },
  { id: 'home-for-the-holidays', title: 'Home for the Holidays', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Home%20for%20the%20Holidays%20.mp3' },
  { id: 'house-full-of-memories', title: 'House Full of Memories', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/House%20Full%20of%20Memories.mp3' },
  { id: 'jingle-night', title: 'Jingle Night', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Jingle%20Night.mp3' },
  { id: 'lakehouse-in-winter', title: 'Lakehouse in Winter', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Lakehouse%20in%20Winter.mp3' },
  { id: 'letters-by-the-fireplace', title: 'Letters by the Fireplace', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Letters%20by%20the%20Fireplace.mp3' },
  { id: 'long-drive-home', title: 'Long Drive Home', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Long%20Drive%20Home.mp3' },
  { id: 'love-notes-in-snow', title: 'Love Notes in Snow', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Love%20Notes%20in%20Snow.mp3' },
  { id: 'merry-melancholy', title: 'Merry & Melancholy', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Merry%20&%20Melancholy.mp3' },
  { id: 'midnight-snowfall', title: 'Midnight Snowfall', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Midnight%20Snowfall.mp3' },
  { id: 'missing-you-this-december', title: 'Missing You This December', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Missing%20You%20This%20December.mp3' },
  { id: 'north-star-glow', title: 'North Star Glow', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/North%20Star%20Glow.mp3' },
  { id: 'northern-glow', title: 'Northern Glow', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Northern%20Glow.mp3' },
  { id: 'old-vinyl-christmas', title: 'Old Vinyl Christmas', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Old%20Vinyl%20Christmas.mp3' },
  { id: 'peppermint-steam', title: 'Peppermint Steam', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Peppermint%20Steam.mp3' },
  { id: 'pine-forest-echo', title: 'Pine Forest Echo', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Pine%20Forest%20Echo.mp3' },
  { id: 'polar-night-pulse', title: 'Polar Night Pulse', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Polar%20Night%20Pulse.mp3' },
  { id: 'reindeer-route', title: 'Reindeer Route', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Reindeer%20Route.mp3' },
  { id: 'silent-light-parade', title: 'Silent Light Parade', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Silent%20Light%20Parade.mp3' },
  { id: 'silver-bells', title: 'Silver Bells', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Silver%20Bells%20.mp3' },
  { id: 'sleighbells-in-the-distance', title: 'Sleighbells in the Distance', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Sleighbells%20in%20the%20Distance.mp3' },
  { id: 'slow-dancing-in-winter', title: 'Slow Dancing in Winter', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Slow%20Dancing%20in%20Winter.mp3' },
  { id: 'snow-on-my-sweater', title: 'Snow on My Sweater', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Snow%20on%20My%20Sweater.mp3' },
  { id: 'snow-dusted-streets', title: 'Snow-Dusted Streets', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Snow-Dusted%20Streets.mp3' },
  { id: 'snowfall-over-coffee', title: 'Snowfall Over Coffee', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Snowfall%20Over%20Coffee%20(1).mp3' },
  { id: 'snowflakes-in-stereo', title: 'Snowflakes in Stereo', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Snowflakes%20in%20Stereo.mp3' },
  { id: 'snowglobe-reverie', title: 'Snowglobe Reverie', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Snowglobe%20Reverie.mp3' },
  { id: 'soft-sleigh-shuffle', title: 'Soft Sleigh Shuffle', url: 'https://kcuhjqhxlnlzuozqhwoa.supabase.co/storage/v1/object/public/Radio/christmas-lofi/Soft%20Sleigh%20Shuffle.mp3' },
];
